name: Test

on:
  pull_request:
    branches:
    - '**'

jobs:
  coverage:
    name: python-code-coverage
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12
    # install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # Running tests
    - name: Running tests
      id: tests
      run: |
        echo "::set-output name=LAST_ENTRY::$(pytest tests/ --cache-clear --cov=graphql_parser | tail -1)"

    # count coverage
    - name: Running tests coverage
      if: always()
      id: coverage
      run: |
        echo 'test_coverage<<EOF' >> $GITHUB_ENV
        echo "$(coverage report --fail-under=80 | tail -1)" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV 
    # Report
    - name: Report test results
      if: always()
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Test case: ${{ steps.tests.outputs.LAST_ENTRY }}\nTest coverage: ${{ env.test_coverage }}'
          })